# Generated by Django 5.2.8 on 2025-12-16 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0032_add_idioma_to_personalshopper_addresskeeper'),
        ('app_whatsapp_integration', '0002_update_whatsapp_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome da instância (ex: 'default')", max_length=100, unique=True)),
                ('status', models.CharField(choices=[('creating', 'Criando'), ('opening', 'Abrindo'), ('open', 'Conectada'), ('close', 'Desconectada'), ('connecting', 'Conectando'), ('unpaired', 'Não pareado'), ('unpaired_idle', 'Não pareado (ocioso)'), ('unknown', 'Desconhecido')], default='unknown', help_text='Status atual da instância', max_length=20)),
                ('qrcode', models.TextField(blank=True, help_text='QR Code para conectar (base64)', null=True)),
                ('qrcode_url', models.URLField(blank=True, help_text='URL do QR Code', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Número de telefone conectado', max_length=20, null=True)),
                ('phone_name', models.CharField(blank=True, help_text='Nome do WhatsApp conectado', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Instância está ativa e sendo usada')),
                ('is_default', models.BooleanField(default=False, help_text='Instância padrão do sistema')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última sincronização com Evolution API', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais da instância')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instância Evolution API',
                'verbose_name_plural': 'Instâncias Evolution API',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvolutionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution_message_id', models.CharField(help_text='ID da mensagem na Evolution API', max_length=100, unique=True)),
                ('phone', models.CharField(help_text='Número de telefone (formato: +5511999999999)', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Recebida'), ('outbound', 'Enviada')], help_text='Direção da mensagem', max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento'), ('location', 'Localização'), ('contact', 'Contato'), ('sticker', 'Sticker'), ('unknown', 'Desconhecido')], default='text', help_text='Tipo de mensagem', max_length=20)),
                ('content', models.TextField(help_text='Conteúdo da mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('error', 'Erro')], default='pending', help_text='Status da mensagem', max_length=20)),
                ('processed', models.BooleanField(default=False, help_text='Mensagem foi processada pelo sistema')),
                ('media_url', models.URLField(blank=True, help_text='URL da mídia (se houver)', null=True)),
                ('media_type', models.CharField(blank=True, help_text='Tipo de mídia (MIME type)', max_length=50, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Payload completo da Evolution API')),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro (se houver)', null=True)),
                ('timestamp', models.DateTimeField(help_text='Timestamp da mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem Evolution API',
                'verbose_name_plural': 'Mensagens Evolution API',
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='whatsappcontact',
            options={'ordering': ['-last_message_at', '-created_at'], 'verbose_name': 'Contato WhatsApp', 'verbose_name_plural': 'Contatos WhatsApp'},
        ),
        migrations.AlterModelOptions(
            name='whatsappmessagelog',
            options={'ordering': ['-timestamp', '-created_at'], 'verbose_name': 'Log de Mensagem WhatsApp', 'verbose_name_plural': 'Logs de Mensagens WhatsApp'},
        ),
        migrations.RemoveIndex(
            model_name='whatsappcontact',
            name='whatsapp_in_phone_n_3f1a6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappcontact',
            name='whatsapp_in_contact_f2a742_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappmessagelog',
            name='whatsapp_in_contact_9e61a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappmessagelog',
            name='whatsapp_in_directi_a49fe4_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappmessagelog',
            name='whatsapp_in_provide_fd7d7f_idx',
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='auto_reply_sent',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='message_text',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='message_timestamp',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='provider_message_id',
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='name',
            field=models.CharField(blank=True, help_text='Nome do contato (do WhatsApp)', max_length=200),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='phone',
            field=models.CharField(help_text='Número do WhatsApp (formato: +5511999999999)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuário vinculado (se for User direto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contato que enviou/recebeu a mensagem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='app_whatsapp_integration.whatsappcontact'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='content',
            field=models.TextField(help_text='Conteúdo da mensagem (texto ou URL de mídia)'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Recebida'), ('outbound', 'Enviada')], default='inbound', help_text='Direção da mensagem', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='message_id',
            field=models.CharField(help_text='ID único da mensagem (do provedor)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='phone',
            field=models.CharField(help_text='Número de telefone (backup se contact for None)', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='timestamp',
            field=models.DateTimeField(help_text='Timestamp da mensagem (do WhatsApp)'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['phone'], name='app_whatsap_phone_9a1708_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['user', 'cliente', 'shopper', 'keeper'], name='app_whatsap_user_id_c47a69_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['phone', '-timestamp'], name='app_whatsap_phone_7bef09_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['contact', '-timestamp'], name='app_whatsap_contact_fbb31b_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['processed', '-timestamp'], name='app_whatsap_process_9e1824_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutioninstance',
            index=models.Index(fields=['name'], name='app_whatsap_name_c03e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutioninstance',
            index=models.Index(fields=['status', 'is_active'], name='app_whatsap_status_8f77bc_idx'),
        ),
        migrations.AddField(
            model_name='evolutionmessage',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contato relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_messages', to='app_whatsapp_integration.whatsappcontact'),
        ),
        migrations.AddField(
            model_name='evolutionmessage',
            name='instance',
            field=models.ForeignKey(help_text='Instância que enviou/recebeu a mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_whatsapp_integration.evolutioninstance'),
        ),
        migrations.AddIndex(
            model_name='evolutionmessage',
            index=models.Index(fields=['instance', '-timestamp'], name='app_whatsap_instanc_4beb7f_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutionmessage',
            index=models.Index(fields=['phone', '-timestamp'], name='app_whatsap_phone_cd1f67_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutionmessage',
            index=models.Index(fields=['contact', '-timestamp'], name='app_whatsap_contact_ced461_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutionmessage',
            index=models.Index(fields=['status', '-timestamp'], name='app_whatsap_status_866c88_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutionmessage',
            index=models.Index(fields=['processed', '-timestamp'], name='app_whatsap_process_988b56_idx'),
        ),
    ]
