# Generated by Django 5.2.2 on 2025-06-05 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0002_personalshopper_cliente_personal_shopper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('privado', 'Privado')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clientes', models.ManyToManyField(related_name='eventos', to='app_marketplace.cliente')),
                ('personal_shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_marketplace.personalshopper')),
                ('produtos', models.ManyToManyField(related_name='eventos', to='app_marketplace.produto')),
            ],
        ),
    ]
