# Generated by Django 5.2.2 on 2025-06-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0003_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalshopper',
            name='nome',
            field=models.TextField(blank=True),
        ),
    ]
