# Generated by Django 5.2.2 on 2025-06-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0004_personalshopper_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalshopper',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalshopper',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalshopper',
            name='pinterest',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalshopper',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalshopper',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalshopper',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
