# Generated by Django 5.2.2 on 2025-06-05 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0005_personalshopper_facebook_personalshopper_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionamentoClienteShopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('seguindo', 'Seguindo'), ('recusado', 'Recusado'), ('bloqueado', 'Bloqueado')], default='solicitado', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_marketplace.cliente')),
                ('personal_shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_marketplace.personalshopper')),
            ],
            options={
                'unique_together': {('cliente', 'personal_shopper')},
            },
        ),
    ]
