# Generated by Django 5.2.2 on 2025-06-05 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0006_relacionamentoclienteshopper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereçoentrega',
            name='cliente',
        ),
        migrations.CreateModel(
            name='EnderecoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, help_text='Ex: Casa, Trabalho, etc.', max_length=50)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('padrao', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='app_marketplace.cliente')),
            ],
            options={
                'verbose_name': 'Endereço de Entrega',
                'verbose_name_plural': 'Endereços de Entrega',
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_marketplace.enderecoentrega'),
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='EndereçoEntrega',
        ),
    ]
