# Generated by Django 5.2.2 on 2025-06-05 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0007_remove_endereçoentrega_cliente_enderecoentrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='produtos',
        ),
        migrations.CreateModel(
            name='ProdutoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_eventos', to='app_marketplace.evento')),
                ('importado_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes', to='app_marketplace.produtoevento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_eventos', to='app_marketplace.produto')),
            ],
            options={
                'unique_together': {('evento', 'produto')},
            },
        ),
    ]
