# Generated by Django 5.2.2 on 2025-06-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0008_remove_evento_produtos_produtoevento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='personal_shopper',
        ),
    ]
