# Generated by Django 5.2.2 on 2025-06-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0011_cupomdesconto_pedido_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='nome',
            new_name='titulo',
        ),
    ]
