# Generated by Django 5.2.2 on 2025-06-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0012_rename_nome_evento_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chave_secreta', models.CharField(max_length=255)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('usado_ultima_vez', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('permissoes', models.TextField(blank=True)),
            ],
        ),
    ]
