# Generated by Django 5.2.2 on 2025-10-16 05:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0013_openaikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='cupomdesconto',
            options={'verbose_name': 'Cupom de Desconto', 'verbose_name_plural': 'Cupons de Desconto'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimentos'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Itens de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='openaikey',
            options={'verbose_name': 'Chave OpenAI', 'verbose_name_plural': 'Chaves OpenAI'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='personalshopper',
            options={'verbose_name': 'Personal Shopper', 'verbose_name_plural': 'Personal Shoppers'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='produtoevento',
            options={'verbose_name': 'Produto de Evento', 'verbose_name_plural': 'Produtos de Eventos'},
        ),
        migrations.AlterModelOptions(
            name='relacionamentoclienteshopper',
            options={'verbose_name': 'Relacionamento Cliente-Shopper', 'verbose_name_plural': 'Relacionamentos Cliente-Shopper'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_marketplace.cupomdesconto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='app_marketplace.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_marketplace.cliente'),
        ),
        migrations.AlterField(
            model_name='personalshopper',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_shoppers', to='app_marketplace.empresa'),
        ),
        migrations.AlterField(
            model_name='personalshopper',
            name='nome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='personalshopper',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalshopper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='app_marketplace.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app_marketplace.empresa'),
        ),
        migrations.CreateModel(
            name='IntentCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_mid', models.CharField(blank=True, help_text='ID msg externa (WhatsApp, etc)', max_length=120)),
                ('texto_bruto', models.TextField()),
                ('interpretado', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('processado', 'Processado'), ('erro', 'Erro')], default='novo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='app_marketplace.cliente')),
                ('personal_shopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_marketplace.personalshopper')),
            ],
            options={
                'verbose_name': 'Intent de Compra',
                'verbose_name_plural': 'Intents de Compra',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido_local', models.CharField(blank=True, help_text='Ex: Vila Angélica - Sorocaba', max_length=100)),
                ('rua', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('capacidade_itens', models.PositiveIntegerField(default=0, help_text='Capacidade aproximada (qtde de volumes)')),
                ('ocupacao_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxa_guarda_dia', models.DecimalField(decimal_places=2, default=0, help_text='R$/dia por volume', max_digits=8)),
                ('taxa_motoboy', models.DecimalField(decimal_places=2, default=0, help_text='Preço base (opcional)', max_digits=8)),
                ('aceita_retirada', models.BooleanField(default=True)),
                ('aceita_envio', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keeper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keeper',
                'verbose_name_plural': 'Keepers',
            },
        ),
        migrations.CreateModel(
            name='OpcaoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retirada_local', 'Retirada local'), ('motoboy', 'Motoboy'), ('correios', 'Correios'), ('courier', 'Courier (FedEx/UPS/DHL)'), ('viajante', 'Viajante')], max_length=20)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('observacoes', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_envio', to='app_marketplace.keeper')),
            ],
            options={
                'verbose_name': 'Opção de Envio',
                'verbose_name_plural': 'Opções de Envio',
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_publico', models.CharField(help_text='Código que o cliente usa para referência', max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor_declarado', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('dimensoes_cm', models.CharField(blank=True, help_text='LxAxP em cm', max_length=50)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('aguardando_receb', 'Aguardando recebimento'), ('recebido', 'Recebido'), ('em_guarda', 'Em guarda'), ('pronto_envio', 'Pronto para envio/retirada'), ('despachado', 'Despachado'), ('entregue', 'Entregue'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado')], default='criado', max_length=20)),
                ('confirmacao_visual', models.CharField(choices=[('nenhuma', '—'), ('aprovado', '👍'), ('amor', '❤️')], default='nenhuma', max_length=20)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('guarda_inicio', models.DateTimeField(blank=True, null=True)),
                ('guarda_fim', models.DateTimeField(blank=True, null=True)),
                ('foto_recebimento', models.ImageField(blank=True, null=True, upload_to='pacotes/')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='app_marketplace.cliente')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacotes', to='app_marketplace.keeper')),
                ('personal_shopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacotes', to='app_marketplace.personalshopper')),
            ],
            options={
                'verbose_name': 'Pacote',
                'verbose_name_plural': 'Pacotes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('aguardando_receb', 'Aguardando recebimento'), ('recebido', 'Recebido'), ('em_guarda', 'Em guarda'), ('pronto_envio', 'Pronto para envio/retirada'), ('despachado', 'Despachado'), ('entregue', 'Entregue'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado')], max_length=20)),
                ('mensagem', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='app_marketplace.pacote')),
            ],
            options={
                'verbose_name': 'Movimento de Pacote',
                'verbose_name_plural': 'Movimentos de Pacotes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pacotes/')),
                ('legenda', models.CharField(blank=True, max_length=140)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app_marketplace.pacote')),
            ],
            options={
                'verbose_name': 'Foto de Pacote',
                'verbose_name_plural': 'Fotos de Pacotes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto'), ('link_externo', 'Link Externo')], max_length=20)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('pendente', 'Pendente'), ('pago', 'Pago'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='criado', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entrada_percent', models.DecimalField(decimal_places=2, default=0, help_text='Ex: 50.00 = 50%', max_digits=5)),
                ('gateway_ref', models.CharField(blank=True, help_text='ID do link/QR no provedor', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_marketplace.pedido')),
            ],
            options={
                'verbose_name': 'Pagamento Intent',
                'verbose_name_plural': 'Pagamentos Intent',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Ex: 10.00 = 10%', max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('favorecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='app_marketplace.pagamentointent')),
            ],
            options={
                'verbose_name': 'Split de Pagamento',
                'verbose_name_plural': 'Splits de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='PedidoPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(blank=True, help_text='guarda, reembalagem, envio, etc.', max_length=50)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_relacionados', to='app_marketplace.pacote')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_relacionados', to='app_marketplace.pedido')),
            ],
            options={
                'verbose_name': 'Pedido-Pacote',
                'verbose_name_plural': 'Pedidos-Pacotes',
            },
        ),
    ]
