# Generated by Django 5.2.2 on 2025-10-24 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0014_alter_categoria_options_alter_cliente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_tokens', to='app_marketplace.personalshopper')),
            ],
            options={
                'verbose_name': 'Token de Vinculação',
                'verbose_name_plural': 'Tokens de Vinculação',
            },
        ),
        migrations.CreateModel(
            name='KeeperOnboardingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeper_tokens_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keeper_token_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Cadastro Keeper',
                'verbose_name_plural': 'Tokens de Cadastro Keeper',
            },
        ),
        migrations.CreateModel(
            name='ShopperOnboardingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Telefone que vai usar (opcional)', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopper_tokens_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopper_token_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Cadastro Shopper',
                'verbose_name_plural': 'Tokens de Cadastro Shopper',
            },
        ),
        migrations.CreateModel(
            name='WhatsappGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text='ID do grupo no WhatsApp', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nome do grupo', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('auto_approve_orders', models.BooleanField(default=False, help_text='Aprovar pedidos automaticamente')),
                ('send_notifications', models.BooleanField(default=True, help_text='Enviar notificações de status')),
                ('max_participants', models.IntegerField(default=100, help_text='Máximo de participantes')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_groups', to='app_marketplace.keeper')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_whatsapp_groups', to=settings.AUTH_USER_MODEL)),
                ('shopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_groups', to='app_marketplace.personalshopper')),
            ],
            options={
                'verbose_name': 'Grupo WhatsApp',
                'verbose_name_plural': 'Grupos WhatsApp',
                'ordering': ['-last_activity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsappParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Número do WhatsApp', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Nome no WhatsApp', max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_participations', to='app_marketplace.cliente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app_marketplace.whatsappgroup')),
            ],
            options={
                'verbose_name': 'Participante WhatsApp',
                'verbose_name_plural': 'Participantes WhatsApp',
                'ordering': ['-joined_at'],
                'unique_together': {('group', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='WhatsappOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('paid', 'Pago'), ('purchased', 'Comprado'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('products', models.JSONField(default=list, help_text='Lista de produtos do pedido')),
                ('delivery_method', models.CharField(blank=True, help_text='Método de entrega escolhido', max_length=50)),
                ('delivery_address', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_orders', to='app_marketplace.cliente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_marketplace.whatsappgroup')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_marketplace.whatsappparticipant')),
            ],
            options={
                'verbose_name': 'Pedido WhatsApp',
                'verbose_name_plural': 'Pedidos WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='ID da mensagem no WhatsApp', max_length=100, unique=True)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento'), ('location', 'Localização'), ('contact', 'Contato')], default='text', max_length=20)),
                ('content', models.TextField(help_text='Conteúdo da mensagem')),
                ('media_url', models.URLField(blank=True, help_text='URL da mídia (se houver)')),
                ('timestamp', models.DateTimeField(help_text='Quando foi enviada')),
                ('processed', models.BooleanField(default=False, help_text='Se foi processada pelo sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_marketplace.whatsappgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app_marketplace.whatsappparticipant')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsappProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image_urls', models.JSONField(default=list, help_text='URLs das imagens')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Produto em destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_marketplace.whatsappgroup')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_marketplace.whatsappmessage')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_products', to='app_marketplace.whatsappparticipant')),
            ],
            options={
                'verbose_name': 'Produto WhatsApp',
                'verbose_name_plural': 'Produtos WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
