# Generated by Django 5.2.2 on 2025-10-24 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0015_grouplinkrequest_keeperonboardingtoken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={'ordering': ['nome'], 'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimentos'},
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='email',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='estabelecimentos',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='categorias',
            field=models.JSONField(default=list, help_text='Categorias de produtos vendidos'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='cidade',
            field=models.CharField(default='Orlando', max_length=100),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='estado',
            field=models.CharField(default='FL', max_length=50),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='horario_funcionamento',
            field=models.TextField(blank=True, help_text='Ex: Seg-Sex: 9h-18h, Sáb: 9h-14h'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='pais',
            field=models.CharField(default='USA', max_length=50),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='whatsappproduct',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras do produto', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsappproduct',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, help_text='Onde o produto pode ser encontrado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app_marketplace.estabelecimento'),
        ),
        migrations.AddField(
            model_name='whatsappproduct',
            name='localizacao_especifica',
            field=models.CharField(blank=True, help_text='Ex: Corredor 3, Prateleira A, Seção de Perfumes', max_length=200),
        ),
        migrations.AddField(
            model_name='whatsappproduct',
            name='sku_loja',
            field=models.CharField(blank=True, help_text='SKU ou código interno da loja', max_length=50),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='endereco',
            field=models.TextField(default='', help_text='Endereço completo'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='nome',
            field=models.CharField(help_text='Nome do estabelecimento', max_length=200),
        ),
    ]
