# Generated by Django 5.2.8 on 2025-11-27 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0016_alter_estabelecimento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comercial', models.CharField(blank=True, help_text='Nome comercial do agente', max_length=200)),
                ('bio_agente', models.TextField(blank=True, help_text='Biografia como agente KMN')),
                ('score_keeper', models.DecimalField(decimal_places=2, default=5.0, help_text='Score como Keeper (0-10)', max_digits=5)),
                ('score_shopper', models.DecimalField(decimal_places=2, default=5.0, help_text='Score como Shopper (0-10)', max_digits=5)),
                ('ativo_como_keeper', models.BooleanField(default=False)),
                ('ativo_como_shopper', models.BooleanField(default=False)),
                ('verificado_kmn', models.BooleanField(default=False, help_text='Verificado pela rede KMN')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('keeper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agente_profile', to='app_marketplace.keeper')),
                ('personal_shopper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agente_profile', to='app_marketplace.personalshopper')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agente KMN',
                'verbose_name_plural': 'Agentes KMN',
                'ordering': ['-score_keeper', '-score_shopper'],
            },
        ),
        migrations.CreateModel(
            name='RoleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidos_como_keeper', models.PositiveIntegerField(default=0)),
                ('valor_total_como_keeper', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('satisfacao_media_keeper', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('pedidos_como_shopper', models.PositiveIntegerField(default=0)),
                ('valor_total_como_shopper', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('satisfacao_media_shopper', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_clientes_atendidos', models.PositiveIntegerField(default=0)),
                ('total_agentes_parceiros', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='app_marketplace.agente')),
            ],
            options={
                'verbose_name': 'Estatísticas de Papel',
                'verbose_name_plural': 'Estatísticas de Papéis',
            },
        ),
        migrations.CreateModel(
            name='ClienteRelacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forca_relacao', models.DecimalField(decimal_places=2, default=50.0, help_text='Força da relação (0-100)', max_digits=5)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('bloqueada', 'Bloqueada'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('total_pedidos', models.PositiveIntegerField(default=0)),
                ('valor_total_pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ultimo_pedido', models.DateTimeField(blank=True, null=True)),
                ('satisfacao_media', models.DecimalField(decimal_places=2, default=5.0, help_text='Satisfação média (0-10)', max_digits=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_cliente', to='app_marketplace.agente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_agente', to='app_marketplace.cliente')),
            ],
            options={
                'verbose_name': 'Relação Cliente-Agente',
                'verbose_name_plural': 'Relações Cliente-Agente',
                'ordering': ['-forca_relacao', '-ultimo_pedido'],
                'unique_together': {('cliente', 'agente')},
            },
        ),
        migrations.CreateModel(
            name='EstoqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
                ('quantidade_reservada', models.PositiveIntegerField(default=0)),
                ('localizacao_especifica', models.CharField(blank=True, help_text='Ex: Prateleira A3, Corredor 5', max_length=200)),
                ('preco_custo', models.DecimalField(decimal_places=2, help_text='Preço de custo do agente', max_digits=10)),
                ('preco_base', models.DecimalField(decimal_places=2, help_text='Preço base para a rede KMN', max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('disponivel_para_rede', models.BooleanField(default=True, help_text='Disponível para outros agentes da rede')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='app_marketplace.agente')),
                ('estabelecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_items', to='app_marketplace.estabelecimento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_items', to='app_marketplace.produto')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['-atualizado_em'],
                'unique_together': {('agente', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_base', models.DecimalField(decimal_places=2, help_text='Preço base do agente origem', max_digits=10)),
                ('preco_oferta', models.DecimalField(decimal_places=2, help_text='Preço final da oferta', max_digits=10)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('exclusiva_para_clientes', models.BooleanField(default=False, help_text='Oferta apenas para clientes do agente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valida_ate', models.DateTimeField(blank=True, null=True)),
                ('agente_ofertante', models.ForeignKey(help_text='Agente que está oferecendo', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_feitas', to='app_marketplace.agente')),
                ('agente_origem', models.ForeignKey(help_text='Agente que possui o produto', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_origem', to='app_marketplace.agente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='app_marketplace.produto')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['preco_oferta', '-criado_em'],
                'unique_together': {('produto', 'agente_ofertante')},
            },
        ),
        migrations.CreateModel(
            name='TrustlineKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_confianca_a_para_b', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('nivel_confianca_b_para_a', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('perc_shopper', models.DecimalField(decimal_places=2, default=60.0, help_text='% para o fornecedor (Shopper)', max_digits=5)),
                ('perc_keeper', models.DecimalField(decimal_places=2, default=40.0, help_text='% para o dono do cliente (Keeper)', max_digits=5)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pendente', 'Pendente'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('permite_indicacao', models.BooleanField(default=True)),
                ('perc_indicacao', models.DecimalField(decimal_places=2, default=5.0, help_text='% para indicação', max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agente_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustlines_como_a', to='app_marketplace.agente')),
                ('agente_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustlines_como_b', to='app_marketplace.agente')),
            ],
            options={
                'verbose_name': 'Trustline KMN',
                'verbose_name_plural': 'Trustlines KMN',
                'ordering': ['-nivel_confianca_a_para_b', '-aceito_em'],
                'unique_together': {('agente_a', 'agente_b')},
            },
        ),
    ]
