# Generated by Django 5.2.8 on 2025-11-28 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0017_agente_rolestats_clienterelacao_estoqueitem_oferta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.JSONField(blank=True, default=dict, help_text='Informações de contato (telefone, email, WhatsApp, etc.)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados adicionais do cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='keeper',
            field=models.ForeignKey(blank=True, help_text="Keeper que fará a entrega (null se tipo_cliente='do_shopper')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_como_keeper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='preco_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço base (custo) - P_base', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='preco_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço final pago pelo cliente - P_final', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='shopper',
            field=models.ForeignKey(blank=True, help_text='Shopper que criou/vendeu o pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_como_shopper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('do_shopper', 'Cliente do Shopper'), ('do_keeper', 'Cliente do Keeper')], help_text='Tipo de cliente: do_shopper ou do_keeper', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Shopper que criou este produto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CarteiraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(help_text='Nome para exibição da carteira', max_length=200)),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais da carteira')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteiras_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carteira de Clientes',
                'verbose_name_plural': 'Carteiras de Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text='Carteira à qual este cliente pertence (novo modelo oficial)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='app_marketplace.carteiracliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='carteira_cliente',
            field=models.ForeignKey(blank=True, help_text='Carteira à qual o cliente pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='app_marketplace.carteiracliente'),
        ),
        migrations.CreateModel(
            name='LiquidacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_margem', models.DecimalField(decimal_places=2, help_text='Margem total (P_final - P_base)', max_digits=12)),
                ('valor_evora', models.DecimalField(decimal_places=2, help_text='Valor recebido pela Évora', max_digits=12)),
                ('valor_shopper', models.DecimalField(decimal_places=2, help_text='Valor recebido pelo Shopper', max_digits=12)),
                ('valor_keeper', models.DecimalField(decimal_places=2, default=0, help_text='Valor recebido pelo Keeper', max_digits=12)),
                ('detalhes', models.JSONField(default=dict, help_text='Detalhes do cálculo (taxas, percentuais, etc.)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('calculada', 'Calculada'), ('liquidada', 'Liquidada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('liquidado_em', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacao', to='app_marketplace.pedido')),
            ],
            options={
                'verbose_name': 'Liquidação Financeira',
                'verbose_name_plural': 'Liquidações Financeiras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LigacaoMesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('forte', 'Mesh Forte'), ('fraca', 'Mesh Fraca')], default='fraca', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('config_financeira', models.JSONField(default=dict, help_text='Configuração financeira da ligação mesh')),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('agente_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacoes_mesh_como_a', to=settings.AUTH_USER_MODEL)),
                ('agente_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacoes_mesh_como_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ligação Mesh',
                'verbose_name_plural': 'Ligações Mesh',
                'ordering': ['-aceito_em', '-criado_em'],
                'unique_together': {('agente_a', 'agente_b')},
            },
        ),
    ]
