# Generated by Django 5.2.8 on 2025-11-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0018_reestruturacao_oficial'),
    ]

    operations = [
    ]
