# Generated by Django 5.2.8 on 2025-11-28 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0019_rename_keeper_to_address_keeper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='keeper',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='keeper',
        ),
        migrations.RemoveField(
            model_name='whatsappgroup',
            name='keeper',
        ),
        migrations.RemoveField(
            model_name='opcaoenvio',
            name='keeper',
        ),
        migrations.RemoveField(
            model_name='keeperonboardingtoken',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='keeperonboardingtoken',
            name='used_by',
        ),
        migrations.CreateModel(
            name='AddressKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido_local', models.CharField(blank=True, help_text='Ex: Vila Angélica - Sorocaba', max_length=100)),
                ('rua', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('capacidade_itens', models.PositiveIntegerField(default=0, help_text='Capacidade aproximada (qtde de volumes)')),
                ('ocupacao_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxa_guarda_dia', models.DecimalField(decimal_places=2, default=0, help_text='R$/dia por volume', max_digits=8)),
                ('taxa_motoboy', models.DecimalField(decimal_places=2, default=0, help_text='Preço base (opcional)', max_digits=8)),
                ('aceita_retirada', models.BooleanField(default=True)),
                ('aceita_envio', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_keeper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address Keeper (Ponto de Guarda)',
                'verbose_name_plural': 'Address Keepers (Pontos de Guarda)',
                'db_table': 'app_marketplace_addresskeeper',
            },
        ),
        migrations.AddField(
            model_name='agente',
            name='address_keeper',
            field=models.OneToOneField(blank=True, help_text='Address Keeper (ponto de guarda) associado a este agente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agente_profile', to='app_marketplace.addresskeeper'),
        ),
        migrations.AddField(
            model_name='opcaoenvio',
            name='address_keeper',
            field=models.ForeignKey(blank=True, help_text='Ponto de guarda que oferece esta opção de envio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_envio', to='app_marketplace.addresskeeper'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='address_keeper',
            field=models.ForeignKey(blank=True, help_text='Ponto de guarda que recebe/guarda este pacote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacotes', to='app_marketplace.addresskeeper'),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='address_keeper',
            field=models.ForeignKey(blank=True, help_text='Address Keeper (ponto de guarda) dono deste grupo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_groups', to='app_marketplace.addresskeeper'),
        ),
        migrations.CreateModel(
            name='AddressKeeperOnboardingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_keeper_tokens_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_keeper_token_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Cadastro Address Keeper',
                'verbose_name_plural': 'Tokens de Cadastro Address Keeper',
            },
        ),
        migrations.DeleteModel(
            name='Keeper',
        ),
        migrations.DeleteModel(
            name='KeeperOnboardingToken',
        ),
    ]
