# Generated by Django 5.2.8 on 2025-11-28 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0022_migrar_dados_estabelecimento_para_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappproduct',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, help_text='Empresa/Estabelecimento onde o produto pode ser encontrado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos_whatsapp', to='app_marketplace.empresa'),
        ),
        migrations.AlterField(
            model_name='estoqueitem',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, help_text='Empresa/Estabelecimento onde o estoque está localizado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_items', to='app_marketplace.empresa'),
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome'], 'verbose_name': 'Empresa/Estabelecimento', 'verbose_name_plural': 'Empresas/Estabelecimentos'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='categorias',
            field=models.JSONField(blank=True, default=list, help_text='Categorias de produtos vendidos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, help_text='Ex: Orlando, Ciudad del Este', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço completo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, help_text='Ex: FL, Alto Paraná', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='horario_funcionamento',
            field=models.TextField(blank=True, help_text='Ex: Seg-Sex: 9h-18h, Sáb: 9h-14h'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(default='Brasil', help_text='País onde está localizada', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='website',
            field=models.URLField(blank=True, help_text='Site da empresa/loja'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ (opcional - para empresas brasileiras)', max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(help_text='Nome da empresa/loja', max_length=200),
        ),
        migrations.DeleteModel(
            name='Estabelecimento',
        ),
    ]
