# Generated by Django 5.2.8 on 2025-11-28 05:30

from django.db import migrations


def migrar_estabelecimentos_para_empresas(apps, schema_editor):
    """
    Migra todos os registros de Estabelecimento para Empresa.
    Preserva todos os dados de Orlando e outros estabelecimentos.
    """
    Estabelecimento = apps.get_model('app_marketplace', 'Estabelecimento')
    Empresa = apps.get_model('app_marketplace', 'Empresa')
    
    estabelecimentos = Estabelecimento.objects.all()
    total = estabelecimentos.count()
    
    print(f"\nMigrando {total} estabelecimento(s) para Empresa...")
    
    for est in estabelecimentos:
        # Criar Empresa com dados do Estabelecimento
        empresa = Empresa.objects.create(
            nome=est.nome,
            cnpj=None,  # Estabelecimentos não têm CNPJ
            email=f"contato@{est.nome.lower().replace(' ', '').replace("'", '').replace('.', '')}.com" if est.nome else 'contato@empresa.com',  # Email obrigatório
            telefone=est.telefone or '',
            website=est.website or '',
            endereco=est.endereco or '',
            cidade=est.cidade or '',
            estado=est.estado or '',
            pais=est.pais or 'USA',
            latitude=est.latitude,
            longitude=est.longitude,
            horario_funcionamento=est.horario_funcionamento or '',
            categorias=est.categorias or [],
            ativo=est.ativo,
            criada_em=est.criado_em,
            atualizado_em=est.atualizado_em if hasattr(est, 'atualizado_em') else est.criado_em
        )
        
        # Atualizar ForeignKeys usando apps.get_model para evitar import direto
        try:
            WhatsappProduct = apps.get_model('app_marketplace', 'WhatsappProduct')
            if WhatsappProduct.objects.filter(estabelecimento_id=est.id).exists():
                WhatsappProduct.objects.filter(estabelecimento_id=est.id).update(estabelecimento_id=empresa.id)
        except Exception as e:
            print(f"  AVISO: Erro ao atualizar WhatsappProduct: {e}")
        
        try:
            EstoqueItem = apps.get_model('app_marketplace', 'EstoqueItem')
            if EstoqueItem.objects.filter(estabelecimento_id=est.id).exists():
                EstoqueItem.objects.filter(estabelecimento_id=est.id).update(estabelecimento_id=empresa.id)
        except Exception as e:
            print(f"  AVISO: Erro ao atualizar EstoqueItem: {e}")
        
        print(f"  OK Migrado: {est.nome} ({est.cidade}/{est.estado})")
    
    print(f"\nOK Migracao concluida: {total} estabelecimento(s) migrado(s) para Empresa")


def reverter_migracao(apps, schema_editor):
    """
    Reverte a migração (não é possível recuperar os dados exatamente,
    mas podemos tentar identificar empresas que vieram de estabelecimentos).
    """
    # Esta função não pode reverter completamente porque não sabemos
    # quais empresas vieram de estabelecimentos
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0020_rename_keeper_to_address_keeper'),
    ]

    operations = [
        migrations.RunPython(migrar_estabelecimentos_para_empresas, reverter_migracao),
    ]
