# Generated by Django 5.2.8 on 2025-11-28 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0021_unificar_empresa_estabelecimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoAgora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conteudo', models.CharField(choices=[('video', 'Vídeo'), ('imagem', 'Imagem'), ('produto', 'Produto'), ('texto', 'Texto')], default='produto', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='URL do vídeo', null=True)),
                ('imagem_url', models.URLField(blank=True, help_text='URL da imagem', null=True)),
                ('legenda', models.TextField(blank=True, help_text='Legenda/descrição da publicação')),
                ('preco_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Preço personalizado da oferta (se diferente do produto)', max_digits=10, null=True)),
                ('mesh_type', models.CharField(choices=[('mall', 'Mall (Produto direto)'), ('mesh_forte', 'Mesh Forte (KMN)'), ('mesh_fraca', 'Mesh Fraca (KMN)')], default='mall', help_text='Tipo de mesh KMN', max_length=20)),
                ('spark_score', models.DecimalField(decimal_places=2, default=0.0, help_text='SparkScore Comercial (0-100) - score de relevância', max_digits=5)),
                ('ppa', models.DecimalField(decimal_places=2, default=0.0, help_text='PPA (Potencial Prévio de Ação) 0.0-1.0', max_digits=3)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(help_text='Shopper ou Keeper que criou a publicação', on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_agora', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, help_text='Evento/Campanha/Viagem relacionada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_agora', to='app_marketplace.evento')),
                ('produto', models.ForeignKey(blank=True, help_text='Produto vinculado à publicação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_agora', to='app_marketplace.produto')),
            ],
            options={
                'verbose_name': 'Publicação Ágora',
                'verbose_name_plural': 'Publicações Ágora',
                'ordering': ['-spark_score', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EngajamentoAgora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('view', 'Visualização'), ('like', 'Like'), ('add_carrinho', 'Adicionar ao Carrinho'), ('compartilhar', 'Compartilhar'), ('ver_detalhes', 'Ver Detalhes')], max_length=20)),
                ('view_time_segundos', models.IntegerField(default=0, help_text="Tempo de visualização em segundos (apenas para tipo 'view')")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que interagiu (null para anônimos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engajamentos_agora', to=settings.AUTH_USER_MODEL)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engajamentos', to='app_marketplace.publicacaoagora')),
            ],
            options={
                'verbose_name': 'Engajamento Ágora',
                'verbose_name_plural': 'Engajamentos Ágora',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='publicacaoagora',
            index=models.Index(fields=['-spark_score', '-criado_em'], name='app_marketp_spark_s_71b8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacaoagora',
            index=models.Index(fields=['ativo', '-spark_score'], name='app_marketp_ativo_048732_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacaoagora',
            index=models.Index(fields=['evento', '-spark_score'], name='app_marketp_evento__471359_idx'),
        ),
        migrations.AddIndex(
            model_name='engajamentoagora',
            index=models.Index(fields=['publicacao', 'tipo'], name='app_marketp_publica_6cef93_idx'),
        ),
        migrations.AddIndex(
            model_name='engajamentoagora',
            index=models.Index(fields=['usuario', '-criado_em'], name='app_marketp_usuario_aa1793_idx'),
        ),
    ]
