# Generated by Django 5.2.8 on 2025-11-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0022_publicacaoagora_engajamentoagora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_email',
            field=models.EmailField(blank=True, help_text='Email do cliente', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_nome',
            field=models.CharField(blank=True, help_text='Nome do cliente no momento do pedido', max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp do cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único do pedido (ex: EV-000123)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='Evento/Campanha relacionada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='app_marketplace.evento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='moeda',
            field=models.CharField(default='BRL', help_text='Moeda do pedido (BRL, USD, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do frete', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor subtotal (sem frete e taxas)', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_taxas',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor de taxas adicionais', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_marketplace.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_marketplace.enderecoentrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('criado', 'Criado'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('em_preparacao', 'Em preparação'), ('em_transporte', 'Em transporte'), ('concluido', 'Concluído')], default='criado', max_length=30),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartão de Crédito'), ('pi', 'Pi Network'), ('token', 'Token interno')], help_text='Método de pagamento', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do pagamento', max_digits=10)),
                ('moeda', models.CharField(default='BRL', help_text='Moeda (BRL, USD, etc.)', max_length=3)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado'), ('chargeback', 'Chargeback')], default='criado', max_length=20)),
                ('gateway', models.CharField(help_text='Gateway utilizado (mercadopago, stripe, pagarme, etc.)', max_length=50)),
                ('gateway_payment_id', models.CharField(blank=True, help_text='ID do pagamento no gateway', max_length=100, null=True)),
                ('gateway_checkout_url', models.URLField(blank=True, help_text='URL do checkout/link de pagamento', null=True)),
                ('gateway_qr_code', models.TextField(blank=True, help_text='QR Code (para Pix)', null=True)),
                ('gateway_qr_code_base64', models.TextField(blank=True, help_text='QR Code em base64 (para exibição)', null=True)),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais do pagamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(help_text='Pedido vinculado (1:1)', on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='app_marketplace.pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(help_text='Tipo de evento (payment_created, payment_approved, payment_failed, etc.)', max_length=50)),
                ('payload', models.JSONField(default=dict, help_text='Payload completo do webhook/evento')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Resposta do gateway (se aplicável)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.ForeignKey(help_text='Pagamento relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='app_marketplace.pagamento')),
            ],
            options={
                'verbose_name': 'Transação Gateway',
                'verbose_name_plural': 'Transações Gateway',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['pagamento', '-criado_em'], name='app_marketp_pagamen_246d60_idx'), models.Index(fields=['tipo_evento', '-criado_em'], name='app_marketp_tipo_ev_7e6ddb_idx')],
            },
        ),
    ]
