# Generated by Django 5.2.8 on 2025-11-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0023_pedido_cliente_email_pedido_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustlinekeeper',
            name='tipo_compartilhamento',
            field=models.CharField(choices=[('bidirecional', 'Bidirecional (ambos compartilham)'), ('a_para_b', 'Unidirecional (A → B: A empresta para B)'), ('b_para_a', 'Unidirecional (B → A: B empresta para A)')], default='bidirecional', help_text='Tipo de compartilhamento de carteira de clientes', max_length=20),
        ),
        migrations.AlterField(
            model_name='trustlinekeeper',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('pendente', 'Pendente'), ('suspensa', 'Suspensa'), ('cancelada', 'Encerrada')], default='pendente', max_length=20),
        ),
    ]
