# Generated by Django 5.2.8 on 2025-11-29 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0024_add_tipo_compartilhamento_trustline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantPermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Mensagem opcional explicando a solicitação')),
                ('response_message', models.TextField(blank=True, help_text='Resposta do dono da carteira')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data de expiração da solicitação', null=True)),
                ('carteira_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_received', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='app_marketplace.cliente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='app_marketplace.whatsappgroup')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Permissão de Participante',
                'verbose_name_plural': 'Solicitações de Permissão de Participantes',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['carteira_owner', 'status'], name='app_marketp_carteir_508806_idx'), models.Index(fields=['requested_by', 'status'], name='app_marketp_request_5fcaa7_idx')],
                'unique_together': {('group', 'cliente', 'status')},
            },
        ),
    ]
