# Generated by Django 5.2.8 on 2025-11-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0025_participantpermissionrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantpermissionrequest',
            unique_together={('group', 'cliente')},
        ),
    ]
