# Generated by Django 5.2.8 on 2025-11-29 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0026_alter_participantpermissionrequest_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_file', models.ImageField(help_text='Screenshot do post', upload_to='screenshots/posts/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Largura da imagem em pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Altura da imagem em pixels', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Tamanho do arquivo em bytes', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre a captura')),
                ('captured_by', models.ForeignKey(help_text='Usuário que capturou a imagem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_screenshots', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_screenshots', to='app_marketplace.whatsappgroup')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='app_marketplace.whatsappproduct')),
            ],
            options={
                'verbose_name': 'Screenshot de Post',
                'verbose_name_plural': 'Screenshots de Posts',
                'ordering': ['-captured_at'],
            },
        ),
    ]
