# Generated by Django 5.2.8 on 2025-11-30 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0027_postscreenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappproduct',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Mensagem do WhatsApp que originou este produto (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_marketplace.whatsappmessage'),
        ),
        migrations.AlterField(
            model_name='whatsappproduct',
            name='posted_by',
            field=models.ForeignKey(help_text='Participante que criou/postou este produto', on_delete=django.db.models.deletion.CASCADE, related_name='posted_products', to='app_marketplace.whatsappparticipant'),
        ),
    ]
