# Generated by Django 5.2.8 on 2025-12-01 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0029_migrar_dados_estabelecimento_para_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_from_customer',
            field=models.BooleanField(default=True, help_text='Mensagem veio do cliente'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='read',
            field=models.BooleanField(default=False, help_text='Mensagem foi lida'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Quando foi lida', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_marketplace.whatsappgroup'),
        ),
        migrations.CreateModel(
            name='WhatsappConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(help_text='ID único da conversa', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('new', 'Nova'), ('open', 'Aberta'), ('waiting', 'Aguardando Cliente'), ('pending', 'Pendente'), ('resolved', 'Resolvida'), ('closed', 'Fechada')], default='new', max_length=20)),
                ('tags', models.JSONField(default=list, help_text='Tags para categorizar: vendas, suporte, pedido, urgente, etc.')),
                ('priority', models.IntegerField(choices=[(1, 'Baixa'), (3, 'Normal'), (5, 'Média'), (7, 'Alta'), (9, 'Urgente')], default=3, help_text='Prioridade 1-9 (auto-calculada ou manual)')),
                ('first_message_at', models.DateTimeField(auto_now_add=True, help_text='Primeira mensagem')),
                ('last_message_at', models.DateTimeField(auto_now=True, help_text='Última mensagem')),
                ('first_response_at', models.DateTimeField(blank=True, help_text='Quando foi respondida pela primeira vez', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Quando foi resolvida', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Quando foi fechada', null=True)),
                ('message_count', models.IntegerField(default=0, help_text='Total de mensagens')),
                ('unread_count', models.IntegerField(default=0, help_text='Mensagens não lidas')),
                ('response_time_avg', models.DurationField(blank=True, help_text='Tempo médio de resposta', null=True)),
                ('source', models.CharField(choices=[('group', 'Grupo'), ('direct', 'Direto'), ('after_purchase', 'Pós-Compra'), ('support', 'Suporte')], default='group', help_text='Origem da conversa', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Anotações internas do atendente')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Agente/shopper responsável pelo atendimento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente cadastrado (se vinculado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='app_marketplace.cliente')),
                ('group', models.ForeignKey(blank=True, help_text='Grupo onde iniciou (se veio de grupo)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='app_marketplace.whatsappgroup')),
                ('participant', models.ForeignKey(help_text='Participante/cliente da conversa', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='app_marketplace.whatsappparticipant')),
                ('related_orders', models.ManyToManyField(blank=True, help_text='Pedidos relacionados a esta conversa', related_name='conversations', to='app_marketplace.whatsapporder')),
            ],
            options={
                'verbose_name': 'Conversa WhatsApp',
                'verbose_name_plural': 'Conversas WhatsApp',
                'ordering': ['-last_message_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='ConversationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Conteúdo da nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_notes', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='app_marketplace.whatsappconversation')),
            ],
            options={
                'verbose_name': 'Nota de Conversa',
                'verbose_name_plural': 'Notas de Conversas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Conversa/ticket individual (após compra)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='app_marketplace.whatsappconversation'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['conversation', 'read'], name='app_marketp_convers_fdc7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['sender', 'timestamp'], name='app_marketp_sender__2e3183_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['status', 'assigned_to'], name='app_marketp_status_a38e37_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['group', 'participant'], name='app_marketp_group_i_4a7297_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['cliente', 'status'], name='app_marketp_cliente_10daed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['last_message_at', 'status'], name='app_marketp_last_me_1dd118_idx'),
        ),
    ]
