# Generated by Django 5.2.8 on 2025-12-08 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0030_whatsappmessage_is_from_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_json', models.JSONField(help_text='Dados completos do produto no formato modelo.json')),
                ('nome_produto', models.CharField(db_index=True, help_text='Nome do produto para busca rápida', max_length=500)),
                ('marca', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('imagem_original', models.CharField(blank=True, help_text='Caminho do arquivo de imagem original', max_length=500, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, help_text='Shopper que criou este produto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_json_criados', to=settings.AUTH_USER_MODEL)),
                ('grupo_whatsapp', models.ForeignKey(blank=True, help_text='Grupo WhatsApp onde o produto foi postado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_json', to='app_marketplace.whatsappgroup')),
            ],
            options={
                'verbose_name': 'Produto JSON',
                'verbose_name_plural': 'Produtos JSON',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['nome_produto', 'marca'], name='app_marketp_nome_pr_028ab3_idx'), models.Index(fields=['categoria'], name='app_marketp_categor_491834_idx'), models.Index(fields=['criado_por', '-criado_em'], name='app_marketp_criado__73f981_idx')],
            },
        ),
    ]
