# Generated by Django 5.2.8 on 2025-12-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0032_add_idioma_to_personalshopper_addresskeeper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='empresa',
        ),
    ]
