# Generated by Django 5.2.8 on 2025-12-21 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0036_add_whatsapporder_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do estabelecimento', max_length=150)),
                ('endereco', models.CharField(blank=True, help_text='Endereço completo', max_length=300)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cidade', models.CharField(default='Orlando', help_text='Ex: Orlando, Ciudad del Este', max_length=100)),
                ('estado', models.CharField(default='FL', help_text='Ex: FL, Alto Paraná', max_length=50)),
                ('pais', models.CharField(default='USA', help_text='País onde está localizado', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('website', models.URLField(blank=True, help_text='Site do estabelecimento')),
                ('horario_funcionamento', models.TextField(blank=True, help_text='Ex: Seg-Sex: 9h-18h, Sáb: 9h-14h')),
                ('categorias', models.JSONField(blank=True, default=list, help_text='Categorias de produtos vendidos')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConversaContextualizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('negociando', 'Em Negociação'), ('fechada', 'Fechada (pedido criado)'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('mensagem_inicial_enviada', models.BooleanField(default=False, help_text='Mensagem contextualizada inicial foi enviada')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('conversa', models.ForeignKey(help_text='Conversa WhatsApp vinculada', on_delete=django.db.models.deletion.CASCADE, related_name='contextos', to='app_marketplace.whatsappconversation')),
                ('participante', models.ForeignKey(help_text='Participante que iniciou a conversa', on_delete=django.db.models.deletion.CASCADE, related_name='conversas_contextualizadas', to='app_marketplace.whatsappparticipant')),
            ],
            options={
                'verbose_name': 'Conversa Contextualizada',
                'verbose_name_plural': 'Conversas Contextualizadas',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='CarrinhoInvisivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens', models.JSONField(default=list, help_text="Lista de itens: [{'produto_id': 1, 'quantidade': 2, 'preco': 89.90, 'nome': '...'}]")),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal do carrinho', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total do carrinho (com taxas, se houver)', max_digits=10)),
                ('moeda', models.CharField(default='BRL', help_text='Moeda do carrinho', max_length=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conversa_contextualizada', models.OneToOneField(help_text='Conversa vinculada ao carrinho', on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_invisivel', to='app_marketplace.conversacontextualizada')),
            ],
            options={
                'verbose_name': 'Carrinho Invisível',
                'verbose_name_plural': 'Carrinhos Invisíveis',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='OfertaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta_id', models.CharField(help_text='ID único da oferta para click-to-chat (ex: OFT-12345)', max_length=50, unique=True)),
                ('mensagem_postada', models.TextField(help_text='Mensagem original postada no grupo')),
                ('imagem_url', models.URLField(blank=True, help_text='URL da imagem do produto (do SinapUm)')),
                ('preco_exibido', models.DecimalField(blank=True, decimal_places=2, help_text='Preço exibido na oferta', max_digits=10, null=True)),
                ('moeda', models.CharField(default='BRL', help_text='Moeda (BRL, USD, etc.)', max_length=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(help_text='Shopper que criou a oferta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas_criadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(help_text='Grupo WhatsApp onde foi postado', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='app_marketplace.whatsappgroup')),
                ('produto', models.ForeignKey(help_text='Produto oferecido', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='app_marketplace.produtojson')),
            ],
            options={
                'verbose_name': 'Oferta de Produto',
                'verbose_name_plural': 'Ofertas de Produto',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IntencaoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('emoji', 'Emoji (❤️, 👍, etc.)'), ('texto', 'Texto ("eu quero", "quanto custa?")'), ('pergunta', 'Pergunta sobre o produto'), ('comentario', 'Comentário sobre o produto')], help_text='Tipo de manifestação', max_length=20)),
                ('conteudo', models.TextField(help_text='Conteúdo da manifestação (emoji, texto, etc.)')),
                ('mensagem_id', models.CharField(blank=True, help_text='ID da mensagem no WhatsApp', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(help_text='Participante que manifestou interesse', on_delete=django.db.models.deletion.CASCADE, related_name='intencoes_sociais', to='app_marketplace.whatsappparticipant')),
                ('oferta', models.ForeignKey(help_text='Oferta que gerou a intenção', on_delete=django.db.models.deletion.CASCADE, related_name='intencoes_sociais', to='app_marketplace.ofertaproduto')),
            ],
            options={
                'verbose_name': 'Intenção Social',
                'verbose_name_plural': 'Intenções Sociais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='conversacontextualizada',
            name='oferta',
            field=models.ForeignKey(help_text='Oferta que gerou o click-to-chat', on_delete=django.db.models.deletion.CASCADE, related_name='conversas_contextualizadas', to='app_marketplace.ofertaproduto'),
        ),
        migrations.AddIndex(
            model_name='ofertaproduto',
            index=models.Index(fields=['oferta_id'], name='app_marketp_oferta__a6ea7c_idx'),
        ),
        migrations.AddIndex(
            model_name='ofertaproduto',
            index=models.Index(fields=['grupo', '-criado_em'], name='app_marketp_grupo_i_f4227f_idx'),
        ),
        migrations.AddIndex(
            model_name='ofertaproduto',
            index=models.Index(fields=['produto', 'ativo'], name='app_marketp_produto_603886_idx'),
        ),
        migrations.AddIndex(
            model_name='intencaosocial',
            index=models.Index(fields=['oferta', '-criado_em'], name='app_marketp_oferta__ff6a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='intencaosocial',
            index=models.Index(fields=['participante', '-criado_em'], name='app_marketp_partici_7c92d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intencaosocial',
            unique_together={('oferta', 'participante', 'mensagem_id')},
        ),
        migrations.AddIndex(
            model_name='conversacontextualizada',
            index=models.Index(fields=['oferta', 'status'], name='app_marketp_oferta__7516e1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacontextualizada',
            index=models.Index(fields=['participante', '-iniciada_em'], name='app_marketp_partici_a6fd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacontextualizada',
            index=models.Index(fields=['conversa'], name='app_marketp_convers_fd39d4_idx'),
        ),
    ]
