# Generated by Django 5.2.8 on 2025-11-28 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Número no formato internacional (ex: 5511999999999)', max_length=20, unique=True, verbose_name='Número de Telefone')),
                ('name', models.CharField(blank=True, help_text='Nome do contato', max_length=255, verbose_name='Nome')),
                ('contact_type', models.CharField(choices=[('cliente', 'Cliente Final'), ('keeper', 'Keeper'), ('shopper', 'Personal Shopper'), ('unknown', 'Desconhecido')], db_index=True, default='unknown', help_text='Tipo de contato no sistema', max_length=20, verbose_name='Tipo de Contato')),
                ('is_active', models.BooleanField(default=True, help_text='Se o contato está ativo', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais sobre o contato', verbose_name='Metadados')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário associado a este número (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Contato WhatsApp',
                'verbose_name_plural': 'Contatos WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Recebida'), ('outgoing', 'Enviada')], db_index=True, help_text='Se a mensagem foi recebida ou enviada', max_length=10, verbose_name='Direção')),
                ('message_text', models.TextField(help_text='Conteúdo da mensagem', verbose_name='Texto da Mensagem')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, help_text='ID da mensagem retornado pelo provedor', max_length=255, null=True, verbose_name='ID da Mensagem (Provedor)')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('document', 'Documento'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('location', 'Localização'), ('unknown', 'Desconhecido')], default='text', max_length=20, verbose_name='Tipo de Mensagem')),
                ('processing_status', models.CharField(choices=[('pending', 'Pendente'), ('processed', 'Processada'), ('error', 'Erro'), ('ignored', 'Ignorada')], db_index=True, default='pending', max_length=20, verbose_name='Status de Processamento')),
                ('auto_reply_sent', models.BooleanField(default=False, help_text='Se uma resposta automática foi enviada', verbose_name='Resposta Automática Enviada')),
                ('message_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Quando a mensagem foi enviada/recebida', verbose_name='Timestamp da Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais sobre a mensagem', verbose_name='Metadados')),
                ('contact', models.ForeignKey(help_text='Contato associado à mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_integration.whatsappcontact', verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Log de Mensagem WhatsApp',
                'verbose_name_plural': 'Logs de Mensagens WhatsApp',
                'ordering': ['-message_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['phone_number'], name='whatsapp_in_phone_n_3f1a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['contact_type', 'is_active'], name='whatsapp_in_contact_f2a742_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['contact', '-message_timestamp'], name='whatsapp_in_contact_9e61a3_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['direction', 'processing_status'], name='whatsapp_in_directi_a49fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['provider_message_id'], name='whatsapp_in_provide_fd7d7f_idx'),
        ),
    ]
