"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config


# Configurações de IA
OPENAI_API_KEY = config("OPENAI_API_KEY", default="")

# OpenMind AI - Servidor próprio (SinapUm) - Padrão Railway
AI_SERVICE = config("AI_SERVICE", default="openmind")  # "openmind" ou "openai"
OPENMIND_AI_URL = config("OPENMIND_AI_URL", default="")
OPENMIND_AI_KEY = config("OPENMIND_AI_KEY", default="")
OPENMIND_AI_TIMEOUT = config("OPENMIND_AI_TIMEOUT", default=30, cast=int)
OPENMIND_ORG_MODEL = config("OPENMIND_ORG_MODEL", default="qwen2.5-vl-72b-instruct")

# Agente Ágnosto SinapUm - Para processamento de mensagens WhatsApp
SINAPUM_AGENT_URL = config("SINAPUM_AGENT_URL", default="http://69.169.102.84:8001/api/v1/process-message")
SINAPUM_API_KEY = config("SINAPUM_API_KEY", default=None)
# Fallback: usar mesma chave do OpenMind AI se não especificada
if not SINAPUM_API_KEY:
    SINAPUM_API_KEY = OPENMIND_AI_KEY

# Mapeamento de Prompts do Core_SinapUm
# Define qual tipo_servico do PromptTemplate usar para cada funcionalidade
PROMPT_MAPPING = {
    # Análise de imagens de produtos
    'analise_produto_imagem': 'analise_produto_imagem_v1',
    
    # Adicione outros mapeamentos aqui conforme necessário
    # Exemplo:
    # 'analise_texto': 'analise_texto_v1',
    # 'geracao_descricao': 'geracao_descricao_v1',
}

# Evolution API - WhatsApp Integration
EVOLUTION_API_URL = config("EVOLUTION_API_URL", default="http://69.169.102.84:8004")
EVOLUTION_API_KEY = config("EVOLUTION_API_KEY", default="GKvy6psn-8HHpBQ4HAHKFOXnwjHR-oSzeGZzCaws0xg")
EVOLUTION_INSTANCE_NAME = config("EVOLUTION_INSTANCE_NAME", default="default")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Detectar se está no Railway
import os

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-8j^$b4kv512@8mlg=koq)5iu8#fpqz#=ot8ost*)g^eyexvq!b')
# Detectar Railway por múltiplas variáveis (Railway sempre define PORT e pode definir outras)
IS_RAILWAY = (
    os.getenv('RAILWAY_ENVIRONMENT') is not None or
    os.getenv('RAILWAY_PROJECT_ID') is not None or
    os.getenv('RAILWAY_SERVICE_ID') is not None or
    (os.getenv('PORT') is not None and os.getenv('PGHOST') is not None)
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_RAILWAY  # False no Railway, True local

# Obter domínio do Railway se disponível
RAILWAY_PUBLIC_DOMAIN = os.getenv('RAILWAY_PUBLIC_DOMAIN', 'evora-product.up.railway.app')
RAILWAY_URL = f"https://{RAILWAY_PUBLIC_DOMAIN}"

# Lista completa de origens confiáveis para CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://evora-product.up.railway.app',
    RAILWAY_URL,
    f'https://{RAILWAY_PUBLIC_DOMAIN}',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://localhost',
    'http://127.0.0.1',
]

# Se houver variável de ambiente com domínio adicional (do Railway)
if os.getenv('RAILWAY_PUBLIC_DOMAIN'):
    domain = os.getenv('RAILWAY_PUBLIC_DOMAIN')
    CSRF_TRUSTED_ORIGINS.append(f'https://{domain}')
    
# Se houver variável customizada CSRF_TRUSTED_ORIGINS
if os.getenv('CSRF_TRUSTED_ORIGINS'):
    additional_origins = [origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS').split(',')]
    CSRF_TRUSTED_ORIGINS.extend(additional_origins)

ALLOWED_HOSTS = ['*']  # Permitir todos os hosts

# Configurações de segurança para produção
if IS_RAILWAY:
    SECURE_SSL_REDIRECT = False  # Railway já gerencia SSL
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Cookies - configurações otimizadas para Railway
    # Usar Lax ao invés de None para melhor compatibilidade
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'Lax'  # Lax funciona melhor com HTTPS no Railway
    CSRF_COOKIE_HTTPONLY = False  # Permitir acesso via JavaScript
    CSRF_USE_SESSIONS = False  # Usar cookie ao invés de sessão para CSRF
    CSRF_COOKIE_NAME = 'csrftoken'
    CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
    # Não restringir domínio - Railway gerencia isso
    CSRF_COOKIE_DOMAIN = None
    # Desabilitar verificação estrita de Referer se necessário
    CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
else:
    # Desenvolvimento local - configurações mais permissivas
    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'

# Configurações de logging para Railway
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if IS_RAILWAY else 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if IS_RAILWAY else 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'app_marketplace': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    'drf_yasg',
    
    # Local apps
    'app_marketplace',
    'app_whatsapp_integration',  # Integração WhatsApp via gateway
]

MIDDLEWARE = [
    'app_marketplace.middleware.RailwayHealthCheckMiddleware',  # Primeiro para interceptar healthchecks
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise para servir arquivos estáticos
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuração do banco - SEMPRE PostgreSQL
# Usar variáveis de ambiente ou valores padrão
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('PGDATABASE', 'railway'),
        'USER': os.getenv('PGUSER', 'postgres'),
        'PASSWORD': os.getenv('PGPASSWORD', 'dtzlYwfACCJRCJcZPQpnlKEZgnxKqzMM'),
        'HOST': os.getenv('PGHOST', 'yamanote.proxy.rlwy.net'),
        'PORT': os.getenv('PGPORT', '47941'),
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Para Railway

# Static files directories (para desenvolvimento)
# Nota: Não é necessário incluir app_marketplace/static aqui porque o Django
# automaticamente procura arquivos estáticos em app_name/static/ para cada app instalado
STATICFILES_DIRS = []

# Media files (uploads de imagens)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise para servir arquivos estáticos em produção (Railway)
if IS_RAILWAY:
    # Usar storage simples do WhiteNoise para evitar problemas com manifest
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Templates
TEMPLATES[0]['DIRS'] = [BASE_DIR / "app_marketplace" / "templates"]

LOGIN_REDIRECT_URL = '/home/'

LOGIN_URL = '/login/'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

# Swagger/OpenAPI Settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        },
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': True,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
}

# Redis Cache (opcional)
if IS_RAILWAY:
    # Configurar Redis no Railway se disponível
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
else:
    # Redis local para desenvolvimento
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }

